name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello to First Github Actions Build!!"
      - name: Print goodbye
        run: echo "Great working with Github Actions!!"
